### ISSUE TITLE
Repository should have only 'main' and 'dev' branches!

### ISSUE THREAD

**Issue by hackey9** [ArchXUser/test#1]
Branch with other names are not available in shared repository. 
You should remove 'origin/next' branch, and never push thematic-role branches. They must be only local.

**Comment by ArchXUser** [comment]
Fixed!

**Comment by hackey9** [comment]
GJ =)

'main' branch will contain stable production code.
'dev' branch will have only merge-commits from your local thematical branches.
when sprint ends, code from dev had been reviewed and tested, 'dev' merges with 'main'

**Comment by hackey9** [comment]
more issues:

- repository contains README.md and LICENSE. should not contain (see task)
- .gitignore contains overmuch rules

**dont do anything, just skip this, and be careful next time!**
